name: Build

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      run: nuget restore

    - name: Build
      run: msbuild ./CAB301Phase3/CAB301Project1.sln /p:Configuration=Release
